# Generated by Django 2.2.14 on 2021-02-04 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('totalk_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raising_request_for', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('dateandtime', models.DateTimeField(blank=True, null=True)),
                ('going_out_for', models.CharField(choices=[('Coffee', 'Coffee'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=12, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('interested', models.ManyToManyField(blank=True, related_name='accept', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='totalk_app.Profile')),
            ],
        ),
    ]
