# Generated by Django 2.2.14 on 2021-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalk_app', '0005_auto_20210212_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
