# Generated by Django 2.2.14 on 2021-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalk_app', '0006_profile_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
